version: '3'
services:
  backend:
    image: python-server
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend