version: '3'

services:
  python-service:
    image: python-service
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - python-service